// Generated by CoffeeScript 1.6.3
exports.config = {
  files: {
    javascripts: {
      joinTo: {
        'javascripts/fsm.js': /^app/,
        'javascripts/vendor.js': /^vendor/,
        'test/javascripts/test.js': /^test(\/|\\)(?!vendor)/,
        'test/javascripts/test-vendor.js': /^test(\/|\\)(?=vendor)/
      },
      order: {
        before: []
      }
    },
    stylesheets: {
      joinTo: {
        'stylesheets/fsm.css': /^(app|vendor)/,
        'test/stylesheets/test.css': /^test/
      },
      order: {
        before: [],
        after: []
      }
    },
    templates: {
      joinTo: 'javascripts/app.js'
    }
  },
  plugins: {
    jade: {
      options: {
        pretty: true
      }
    }
  }
};
