// Generated by CoffeeScript 1.4.0

/*
 Finite State Machine Designer
 portions Copyright (c) Binghamton University,
 author: Kyle J. Temkin <ktemkin@binghamton.edu>

 Based on:
 Finite State Machine Designer (http://madebyevan.com/fsm/)
 portions Copyright (c) 2010 Evan Wallace

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {
  var FSMDesigner,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  FSMDesigner = (function() {

    FSMDesigner.prototype.snap_to_padding = 20;

    FSMDesigner.prototype.hit_target_padding = 20;

    FSMDesigner.prototype.undo_history_size = 32;

    FSMDesigner.prototype.originalClick = null;

    FSMDesigner.prototype.cursorVisible = true;

    FSMDesigner.prototype.selectedObject = null;

    FSMDesigner.prototype.currentTransition = null;

    FSMDesigner.prototype.movingObject = false;

    FSMDesigner.prototype.inOutputMode = false;

    FSMDesigner.prototype.textEntryTimeout = null;

    FSMDesigner.prototype.textEnteredRecently = false;

    FSMDesigner.prototype.textUndoDelay = 2000;

    FSMDesigner.prototype.states = [];

    FSMDesigner.prototype.transitions = [];

    FSMDesigner.prototype.undo_stack = [];

    FSMDesigner.prototype.redo_stack = [];

    function FSMDesigner(canvas) {
      var canvas_handlers, event, handler, window_handlers,
        _this = this;
      this.canvas = canvas;
      canvas_handlers = {
        'mousedown': function(e) {
          return _this.handle_mousedown(e);
        },
        'doubleclock': function(e) {
          return _this.handle_doubleclick(e);
        },
        'mousemove': function(e) {
          return _this.handle_mousemove(e);
        },
        'mouseup': function(e) {
          return _this.handle_mouseup(e);
        },
        'mousedown': function(e) {
          return _this.handle_mouseup(e);
        },
        'drop': function(e) {
          return _this.handle_drop(e);
        }
      };
      for (event in canvas_handlers) {
        handler = canvas_handlers[event];
        this.canvas.addEventListener(event, handler, false);
      }
      window_handlers = {
        'keypress': function(e) {
          return _this.handle_keypress(e);
        },
        'keydown': function(e) {
          return _this.handle_keydown(e);
        },
        'keyup': function(e) {
          return _this.handle_keyup(e);
        }
      };
      for (event in window_handlers) {
        handler = window_handlers[event];
        window.addEventListener(event, handler, false);
      }
    }

    FSMDesigner.ModalBehaviors = {
      POINTER: 'pointer',
      CREATE: 'create'
    };

    FSMDesigner.KeyCodes = {
      BACKSPACE: 8,
      SHIFT: 16,
      DELETE: 46,
      UNDO: 26,
      REDO: 25,
      z: 122,
      Z: 90
    };

    FSMDesigner.prototype.clear = function(no_save) {
      if (!no_save) {
        this.save_undo_step();
      }
      this.states = [];
      this.transitions = [];
      this.selected = null;
      this.current_target = null;
      return this.draw();
    };

    FSMDesigner.prototype["delete"] = function(obj) {
      this.delete_state(obj);
      return this.delete_transition(obj);
    };

    FSMDesigner.prototype.delete_state = function(state, no_redraw, no_save) {
      var s, selected, t;
      if (__indexOf.call(this.states, state) < 0) {
        return;
      }
      if (!no_save) {
        this.save_undo_step();
      }
      if (selected === state) {
        selected = null;
      }
      this.states = (function() {
        var _i, _len, _ref, _results;
        _ref = this.states;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          s = _ref[_i];
          if (s !== state) {
            _results.push(s);
          }
        }
        return _results;
      }).call(this);
      this.transitions = (function() {
        var _i, _len, _ref, _results;
        _ref = this.transitions;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          t = _ref[_i];
          if (!transition.connectedTo(state)) {
            _results.push(t);
          }
        }
        return _results;
      }).call(this);
      if (!no_redraw) {
        return this.draw();
      }
    };

    FSMDesigner.prototype.delete_transition = function(transition, no_redraw, no_save) {
      var selected, t;
      if (__indexOf.call(this.transitions, transition) < 0) {
        return;
      }
      if (!no_save) {
        this.save_undo_step();
      }
      if (selected === transition) {
        selected = null;
      }
      this.transitions = (function() {
        var _i, _len, _ref, _results;
        _ref = this.transitions;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          t = _ref[_i];
          if (t !== transition) {
            _results.push(t);
          }
        }
        return _results;
      }).call(this);
      if (!no_redraw) {
        return this.draw();
      }
    };

    FSMDesigner.prototype.export_png = function() {
      var png_data, temp_selected;
      temp_selected = this.selected;
      this.selected = null;
      this.draw();
      png_data = canvas.toDataURL('image/png');
      window.open(png_data, '_blank');
      window.focus();
      this.selected = temp_selected;
      return this.draw();
    };

    FSMDesigner.prototype.find_object_at_position = function(x, y) {
      var state, transition, _i, _j, _len, _len1, _ref, _ref1;
      _ref = this.transitions;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        transition = _ref[_i];
        if (transition.contains_point(x, y)) {
          return transition;
        }
      }
      _ref1 = this.states;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        state = _ref1[_j];
        if (state.contains_point(x, y)) {
          return state;
        }
      }
      return null;
    };

    FSMDesigner.prototype.handle_drop = function(e) {
      e.stopPropagation();
      e.preventDefault();
      if (e.dataTransfer.files.length !== 1) {
        return;
      }
      return this.load_from_file(e.dataTransfer.files[0]);
    };

    FSMDesigner.prototype.load_from_file = function(file) {
      var reader;
      this.save_undo_step();
      reader = new FileReader();
      reader.onload = function(file) {
        return this.unserialize(file.target.result);
      };
      return reader.readAsText(file);
    };

    FSMDesigner.prototype.redo = function() {
      if (this.redo_stack.length === 0) {
        return;
      }
      this.save_undo_step();
      this.recreate_state(this.redo_stack.pop());
      return this.draw();
    };

    FSMDesigner.prototype.save_file_data_uri = function() {
      var content, uri_content;
      content = this.serialize_state();
      uri_content = 'data:application/x-fsm,' + encodeURIComponent(content);
      return document.location.href = uri_content;
    };

    FSMDesigner.prototype.save_undo_step = function() {
      var last_state, state;
      state = this.get_state();
      last_state = this.undo_stack.slice(-1);
      if (FSMDesigner.states_equivalent(state, last_state)) {
        return;
      }
      if (this.undo_stack.length >= this.undo_history_size) {
        this.undo_stack.shift();
      }
      return this.undo_stack.push(state);
    };

    FSMDesigner.prototype.save_redo_step = function() {
      if (this.redo_stack.length >= this.redo_history_size) {
        this.redo_stack.shift();
      }
      return this.redo_stack.push(this.get_state);
    };

    FSMDesigner.prototype.serialize = function() {
      return JSON.stringify(this.get_state());
    };

    FSMDesigner.prototype.undo = function() {
      if (this.undo_stack.length === 0) {
        return;
      }
      this.save_redo_step();
      this.recreate_state(this.undo_stack.pop());
      return this.draw();
    };

    FSMDesigner.states_equivalent = function(a, b) {
      return JSON.stringify(a) === JSON.stringify(b);
    };

    return FSMDesigner;

  })();

}).call(this);
